name: Build Windows7 VM Image and Push to GHCR

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  IMAGE_NAME: win10-novnc
  #ZIP_FILE: MSEdge.Win10.VMware.zip
  ZIP_FILE: win10.iso
  ZIP_URL: https://archive.org/download/tiny-10_202301/tiny10%20x86%20beta%202.iso
  ZIP_CACHE_KEY: win10.iso

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Restore ZIP from GitHub Actions Cache
        id: cache-zip
        uses: actions/cache@v4
        with:
          path: ${{ env.ZIP_FILE }}
          key: ${{ env.ZIP_CACHE_KEY }}

      - name: Install qemu-utils and unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-utils unzip wget
          
      - name: Download ZIP if not cached
        if: steps.cache-zip.outputs.cache-hit != 'true'
        run: |
          echo "Cache miss — downloading from archive.org"
          wget -O $ZIP_FILE $ZIP_URL
          
      - name: Save ZIP to Cache (if downloaded)
        if: steps.cache-zip.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: ${{ env.ZIP_FILE }}
          key: ${{ env.ZIP_CACHE_KEY }}
 
      - name: Convert VMDK to QCOW2
        run: |
          ls -lh
          pwd
          qemu-img create -f qcow2 winlite.qcow2 6G
          ls -lh

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:tiny10 .

      - name: Push to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:tiny10
